### PR TITLE
Correctly propagate the "eof" signal through DAOs and Sinks (Swift).

### PR DESCRIPTION
**Pull request by nbegley**

### CODE REVIEW

**Comment by adamvy** [comment]
EOF is not really intended to be fired as an event from a DAO.  IT's a single to a specific sink telling that sink that the event has finished.

What is your use case?

**Comment by nbegley** [comment]
I'm listening on a DAO, and I'd like to react to the changes caused by a select() once all of the changes have settled, instead of reacting to each put/remove individually.

**Comment by adamvy** [comment]
A select() shouldn't cause changes, select is a read operation.

You .listen() on a DAO if you want to react to write operations against the DAO (.put(), .remove() and .removeAll()).  If your listener is firing too often then you can delay responding to the event by using isMerged on your Listener.  But there's no way for a listener to know when mutations to the DAO are "done" since any client of the DAO can issue a mutation operation at any time.

**Comment by nbegley** [comment]
Thanks Adam, I agree that isMerged sounds like the right way to go.

**Pull request closed without merging**
